services:
  app:
    build: .
    image: ghcr.io/arinji2/ai-backend:latest
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./keys.json:/app/keys.json
    ports:
      - "56:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 200M
