name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        env:
          CONTAINER_NAME: ai-backend
          IMAGE_NAME: ghcr.io/arinji2/ai-backend:latest
        run: |
          ssh -o StrictHostKeyChecking=no github_runner@${{ secrets.VPS_HOST }} << EOF
            docker pull $IMAGE_NAME
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            cd /srv/dockerdata/AI-Backend
            ./startup.sh
            docker image prune -f
          EOF
