name: Go Test and Deploy

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -count=1

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to main branch
        run: |
          git config --local user.email "arinjaydhar205@gmail.com" # Change to your email
          git config --local user.name "Arinji2" # Change to your name
          git checkout main
          git merge development --no-ff
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
